// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpwfaiiaefvhqjhkynyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwd2ZhaWlhZWZ2aHFqaGt5bnl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMjI1NTAsImV4cCI6MjA2OTY5ODU1MH0.ArmpVoh5uQrcF3oqAJuCGeFOlm3RoAHjmFLos54oLgA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});